"use client";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { ArrowDownTrayIcon, ArrowPathIcon, StopIcon } from "@heroicons/react/24/outline";
import Shell from "@/components/Shell";
import { api, eventUrl, exportUrl } from "@/lib/api";
import type { Research } from "@/lib/types";

const labels:Record<string,string>={queued:"排队中",pending:"等待中",running:"研究中",cancelling:"取消中",cancelled:"已取消",completed:"已完成",failed:"失败"};

export default function ResearchPage(){
  const {id}=useParams<{id:string}>(); const [item,setItem]=useState<Research>(); const [versions,setVersions]=useState<Research[]>([]); const [tab,setTab]=useState("report"); const [error,setError]=useState(""); const [follow,setFollow]=useState("");
  const load=useCallback(async()=>{const data=await api<Research>(`/api/research/${id}`);setItem(data);if(data.root_id)api<Research[]>(`/api/research/${id}/versions`).then(setVersions);return data},[id]);
  useEffect(()=>{let timer:ReturnType<typeof setInterval>|undefined;let events:EventSource|undefined;load().then(data=>{if(["completed","failed","cancelled"].includes(data.status))return;events=new EventSource(eventUrl(id));events.addEventListener("progress",e=>setItem(JSON.parse((e as MessageEvent).data)));events.addEventListener("done",()=>{events?.close();load();notify()});events.onerror=()=>{events?.close();timer=setInterval(()=>load().then(x=>{if(["completed","failed","cancelled"].includes(x.status)){clearInterval(timer);notify()}}),2500)}}).catch(e=>setError(e.message));return()=>{events?.close();if(timer)clearInterval(timer)}},[id,load]);
  function notify(){if("Notification" in window){if(Notification.permission==="granted")new Notification("深度研究助手",{body:"研究任务状态已更新"});else if(Notification.permission==="default")Notification.requestPermission()}}
  async function action(kind:"cancel"|"retry"){try{const out=await api<{research_id?:string}>(`/api/research/${id}/${kind}`,{method:"POST"});if(out.research_id)location.href=`/research/${out.research_id}`;else load()}catch(e){setError(e instanceof Error?e.message:"操作失败")}}
  async function supplement(e:FormEvent){e.preventDefault();if(!item)return;try{const out=await api<{research_id:string}>("/api/research",{method:"POST",body:JSON.stringify({topic:item.topic,goal:item.goal,date_range:item.date_range,region:item.region,audience:item.audience,depth:item.depth,parent_id:item.research_id,follow_up:follow})});location.href=`/research/${out.research_id}`}catch(e){setError(e instanceof Error?e.message:"提交失败")}}
  if(!item)return <Shell><p>{error||"正在载入研究任务…"}</p></Shell>;
  const active=["queued","pending","running","cancelling"].includes(item.status);
  return <Shell><div style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"flex-start"}}><div><p className="eyebrow">Research · V{item.version}</p><h1>{item.report?.title||item.topic}</h1><p className="lede">{item.goal||`${item.region} · ${item.date_range} · 面向${item.audience}`}</p></div><span className={`badge ${item.status}`}>{labels[item.status]}</span></div>
    {versions.length>1&&<div className="actions" style={{marginTop:18}}>{versions.map(v=><Link key={v.research_id} className={`btn ${v.research_id===id?"btn-primary":"btn-secondary"}`} href={`/research/${v.research_id}`}>V{v.version}</Link>)}</div>}
    {active&&<section className="card card-pad" style={{marginTop:24}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:10}}><strong>{item.current_step}</strong><span className="meta">{item.progress}%</span></div><div className="progress-track"><div className="progress-fill" style={{width:`${item.progress}%`}}/></div><div className="meta" style={{marginTop:12}}>第 {item.process?.iterations||0}/{item.limits.max_rounds} 轮 · 搜索 {item.usage.searches}/{item.limits.max_searches} · 模型调用 {item.usage.model_calls}/{item.limits.max_model_calls}</div>{item.status!=="cancelling"&&<button className="btn btn-danger" style={{marginTop:16}} onClick={()=>action("cancel")}><StopIcon width={17}/>取消任务</button>}</section>}
    {item.friendly_error&&<div className="error" style={{marginTop:20}}>{item.friendly_error} <button className="btn btn-secondary" onClick={()=>action("retry")}><ArrowPathIcon width={16}/>重试</button></div>}
    {item.limited&&<div className="error" style={{marginTop:20}}>研究已使用当前材料生成报告：{item.limit_reason}</div>}
    <div className="tabs"><button className={`tab ${tab==="report"?"active":""}`} onClick={()=>setTab("report")}>研究报告</button><button className={`tab ${tab==="process"?"active":""}`} onClick={()=>setTab("process")}>研究过程</button><button className={`tab ${tab==="sources"?"active":""}`} onClick={()=>setTab("sources")}>来源 · {item.sources.length}</button></div>
    {tab==="report"&&<ReportView item={item}/>} {tab==="process"&&<ProcessView item={item}/>} {tab==="sources"&&<SourcesView item={item}/>} 
    {item.status==="completed"&&<><div className="actions" style={{marginTop:30}}>{["markdown","html","pdf"].map(kind=><a key={kind} className="btn btn-secondary" href={exportUrl(id,kind)}><ArrowDownTrayIcon width={16}/>导出 {kind.toUpperCase()}</a>)}</div><form className="card card-pad" onSubmit={supplement} style={{marginTop:24}}><h2>补充研究，生成 V{item.version+1}</h2><div className="field"><label>补充要求</label><textarea required value={follow} onChange={e=>setFollow(e.target.value)} placeholder="例如：补充中国市场的监管与落地案例，并重新评估风险。"/></div><button className="btn btn-primary" style={{marginTop:14}}>生成新版本</button></form></>}
  </Shell>;
}

function ReportView({item}:{item:Research}){const report=item.report;if(!report)return <p className="meta">报告生成后会显示在这里。当前已保存 {item.sources.length} 个来源和 {item.process?.steps.length||0} 个研究步骤。</p>;return <article className="report"><div className="card card-pad"><p className="eyebrow">摘要 · 置信度 {item.confidence?.overall||"low"}</p><p>{report.summary}</p></div><h2>背景</h2><p>本报告围绕“{item.topic}”展开，研究范围为 {item.region} / {item.date_range}，目标读者为{item.audience}。</p>{report.sections.map((s,i)=><section key={`${s.heading}-${i}`}><h2>{s.heading}</h2><p>{s.body}</p></section>)}<h2>关键结论</h2><ol>{report.key_conclusions.map((c,i)=><li key={i}>{c.text} {c.is_model_inference||!c.sources.length?<strong>（模型推断）</strong>:c.sources.map((s,j)=><a key={j} href={s.url} target="_blank" rel="noreferrer"> [{j+1}]</a>)}</li>)}</ol><h2>风险与局限</h2><ul>{item.confidence?.notes.map((x,i)=><li key={i}>{x}</li>)}</ul><h2>遗留问题</h2><ul>{report.open_questions.map((x,i)=><li key={i}>{x}</li>)}</ul></article>}
function ProcessView({item}:{item:Research}){return <div className="timeline">{item.process?.steps.map((s,i)=><div className="timeline-item" key={i}><strong>{stepName(s.type)} · 第 {s.round} 轮</strong><div className="meta" style={{marginTop:5}}>{JSON.stringify(s.detail,null,2)}</div></div>)||<p className="meta">暂无步骤</p>}</div>}
function SourcesView({item}:{item:Research}){return <div className="list">{item.sources.map((s,i)=><a className="list-item" href={s.url} target="_blank" rel="noreferrer" key={s.url}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><strong>[{i+1}] {s.title||s.url}</strong><span className="badge">{s.extraction_status==="full"?"正文":"搜索摘要"}</span></div><p className="meta">{s.site_name} · 访问于 {s.accessed_at}</p><p style={{marginBottom:0,color:"#526078"}}>{s.snippet.slice(0,240)}</p></a>)}</div>}
function stepName(x:string){return ({plan:"规划",search:"检索",summarize:"总结",judge:"充分性判断",warning:"降级处理"} as Record<string,string>)[x]||x}
